"""Code reader interface."""

from __future__ import annotations
from typing import Protocol


class CodeReaderProtocol(Protocol):
    def find_enclosing_function(self, file_path: str, line: int) -> str: ...
    def get_function_body(self, file_path: str, function_name: str) -> str: ...
    def find_callees(self, file_path: str, function_name: str) -> list[str]: ...
    def find_imports(self, file_path: str) -> list[str]: ...
    def read_context(self, file_path: str, line: int, context: int = 10) -> str: ...
